import type { FastifyInstance } from 'fastify'

const pageRoutes: Record<string, string> = {
  '/': 'index.html',
  '/product': 'pages/product.html',
  '/features': 'pages/features.html',
  '/pricing': 'pages/pricing.html',
  '/about': 'pages/about.html',
  '/contact': 'pages/contact.html',
  '/documentation': 'pages/documentation.html',
  '/demo': 'pages/other/demo.html',
  '/legal': 'pages/other/legal.html',
  '/privacy': 'pages/other/privacy.html',
  '/resources': 'pages/other/resources.html',
  '/solutions': 'pages/other/solutions.html',
  '/login': 'onboarding/login.html',
  '/register': 'onboarding/register.html',
  '/business-setup': 'onboarding/business-setup.html',
  '/feature-setup': 'onboarding/feature-setup.html',
  '/store-setup': 'onboarding/store-setup.html',
  '/staff-setup': 'onboarding/staff-setup.html',
  '/product-setup': 'onboarding/product-setup.html',
  '/onboarding-completion': 'onboarding/onboarding-completion.html',
  '/forgot-password': 'onboarding/forgot-password.html',
  '/reset-password': 'onboarding/reset-password.html',
  '/forgot-pin': 'onboarding/forgot-pin.html',
  '/admin': 'admin/index.html',
  '/admin/sales-management': 'admin/sales-management.html',
  '/admin/product-and-inventory': 'admin/product-and-inventory.html',
  '/admin/pos-session-monitor': 'admin/pos_session_monitor.html',
  '/admin/staff-and-role-management': 'admin/staff_and_role-management.html',
  '/admin/customer-management': 'admin/customer-management.html',
  '/admin/loyalty-and-points': 'admin/loyalty_and_points.html',
  '/admin/analytics': 'admin/analytics.html',
  '/admin/branch-management': 'admin/branch-management.html',
  '/admin/settings': 'admin/settings.html',
  '/admin/profile': 'admin/profile.html',
  '/admin/notifications': 'admin/notifications.html',
  '/admin/audit-logs': 'admin/audit-logs.html',
  '/cashier': 'cashier/index.html',
  '/cashier/sales': 'cashier/sales.html',
  '/cashier/customers': 'cashier/customers.html',
  '/cashier/shift': 'cashier/shift.html',
  '/cashier/returns': 'cashier/returns.html',
  '/cashier/profile': 'cashier/profile.html',
  '/superadmin': 'superadmin/index.html',
  '/superadmin/businesses': 'superadmin/businesses.html',
  '/superadmin/billing': 'superadmin/billing.html',
  '/superadmin/audit-logs': 'superadmin/audit-logs.html',
  '/superadmin/analytics': 'superadmin/analytics.html',
  '/superadmin/notifications': 'superadmin/notifications.html',
  '/superadmin/settings': 'superadmin/settings.html',
  '/superadmin/profile': 'superadmin/profile.html',
  '/manager': 'manager/index.html',
  '/manager/analytics': 'manager/analytics.html',
  '/manager/cashier': 'manager/cashier.html',
  '/manager/customers': 'manager/customers.html',
  '/manager/inventory': 'manager/inventory.html',
  '/manager/live-monitor': 'manager/live_monitor.html',
  '/manager/loyalty': 'manager/loyalty.html',
  '/manager/notifications': 'manager/notifications.html',
  '/manager/profile': 'manager/profile.html',
  '/manager/reports': 'manager/reports.html',
  '/manager/sales': 'manager/sales.html',
  '/manager/shifts': 'manager/shifts.html',
}

export async function registerPageRoutes(fastify: FastifyInstance) {
  for (const [route, file] of Object.entries(pageRoutes)) {
    fastify.get(route, (_req, reply) => reply.sendFile(file))
  }
}
